export {default as HomePage} from "./Home-Page/Home-Page/Home-Page"
export {default as ModalSearch} from "./Home-Page/Home-Page/ModalSearch/ModalSearch"
export {default as ActivityPage} from "./Activity-Page/Activity-Page"
export {default as ResultPage} from "./Home-Page/Home-Page/Result-Page/Result-Page"
export {default as ArticlePage} from "./Home-Page/Home-Page/Article-Page/Article-Page"
export {default as MencariNarasumberPage} from "./Mencari-Narasumber-Page/Mencari-Narasumber-Page"
